version: '2.3'

services:
  tat_webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tat_webapp
    restart: unless-stopped
    depends_on:
      - tatDatabase
    ports:
      - "8109:8009"
      - "8081:8080"
    mem_limit: 4g
    logging:
      options:
        max-size: "15m"
        max-file: "3"
      driver: "json-file"
    volumes: 
      - /opt/tat/files
      - /opt/tat/lucene
    command: ["./wait-for-it.sh", "tatDatabase:3306","--","catalina.sh", "run"]


  tatDatabase:
    image: mariadb:10.3
    container_name: tatDatabase
    restart: unless-stopped
    ports:
    - "3456:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=tat_user \"--password=tat_pw_11\" --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 5
    environment:
    - MYSQL_USER=tat_user
    - MYSQL_PASSWORD=tat_pw_11
    - MYSQL_ROOT_PASSWORD=tat_pw_11
    - MYSQL_DATABASE=tat_db

